let controlcambio = [
  {
    Id_solicitante : 2,
    Id_evaluador : null,
    Id_verificador :null,
    Id_administrador : null,
    Id_responsable : null,
    Id_servicio : 1,
    Descripcion_Control_Cambio : "Esto es una descripcion de control de cambio",
    Nombre_Control_Cambio : "Primer control de cambio",
    Estatus_Control_Cambio : 1,
    Fecha_Solicitud : "12/23/2019",
    //Fecha_Inicio : req.body.Fecha_Inicio,
    //Fecha_Final : req.body.Fecha_Final,
    //Fecha_Verificacion : req.body.Fecha_Verificacion,
    //Estado_cargo : req.body.Estado_cargo,
    Prioridad_CC : 3,
  },
  {
    Id_solicitante : 2,
    Id_evaluador : null,
    Id_verificador :null,
    Id_administrador : null,
    Id_responsable : null,
    Id_servicio : 2,
    Descripcion_Control_Cambio : "Cambio de pc para Ventas",
    Nombre_Control_Cambio : "Pc Ventas",
    Estatus_Control_Cambio : 1,
    Fecha_Solicitud : "11/23/2020",
    //Fecha_Inicio : req.body.Fecha_Inicio,
    //Fecha_Final : req.body.Fecha_Final,
    //Fecha_Verificacion : req.body.Fecha_Verificacion,
    //Estado_cargo : req.body.Estado_cargo,
    Prioridad_CC : 3,
  },
  {
    Id_solicitante : 2,
    Id_evaluador : null,
    Id_verificador :null,
    Id_administrador : null,
    Id_responsable : null,
    Id_servicio : 3,
    Descripcion_Control_Cambio : "Cntrol de cambio para la Telefonia del centro Comercial Sambil Margarita",
    Nombre_Control_Cambio : "Telefonia Sambil M.",
    Estatus_Control_Cambio : 2,
    Fecha_Solicitud : "11/23/2019",
    //Fecha_Inicio : req.body.Fecha_Inicio,
    //Fecha_Final : req.body.Fecha_Final,
    //Fecha_Verificacion : req.body.Fecha_Verificacion,
    //Estado_cargo : req.body.Estado_cargo,
    Prioridad_CC : 2,
  },
  {
    Id_solicitante : 4,
    Id_evaluador : 1,
    Id_verificador :null,
    Id_administrador : 2,
    Id_responsable : 3,
    Id_servicio : 4,
    Descripcion_Control_Cambio : "Cambio de cableado para la telefonia de PCA",
    Nombre_Control_Cambio : "Cambio de Cableado PCA",
    Estatus_Control_Cambio : 3,
    Fecha_Solicitud : "10/23/2019",
    Fecha_Inicio : "12/23/2019",
    Fecha_Final : "12/23/2019",
    //Fecha_Verificacion : req.body.Fecha_Verificacion,
    //Estado_cargo : req.body.Estado_cargo,
    Prioridad_CC : 1,
  },
  {
    Id_solicitante : 2,
    Id_evaluador : 3,
    Id_verificador :null,
    Id_administrador : 2,
    Id_responsable : 1,
    Id_servicio : 4,
    Descripcion_Control_Cambio : "Cambio de Infraestructura de la oficina de Administracion",
    Nombre_Control_Cambio : "Cambio de Infraestructura",
    Estatus_Control_Cambio : 4,
    Fecha_Solicitud : "09/23/2019",
    Fecha_Inicio : "12/23/2019",
    Fecha_Final : "12/23/2019",
    //Fecha_Verificacion : req.body.Fecha_Verificacion,
    //Estado_cargo : req.body.Estado_cargo,
    Prioridad_CC :3,
  },
  {
    Id_solicitante : 2,
    Id_evaluador : 3,
    Id_verificador :null,
    Id_administrador : 2,
    Id_responsable : 1,
    Id_servicio : 2,
    Descripcion_Control_Cambio : "Administracion de tareas",
    Nombre_Control_Cambio : "Cambio de tareas",
    Estatus_Control_Cambio : 5,
    Fecha_Solicitud : "08/23/2020",
    Fecha_Inicio : "12/23/2019",
    Fecha_Final : "12/23/2019",
    //Fecha_Verificacion : req.body.Fecha_Verificacion,
    //Estado_cargo : req.body.Estado_cargo,
    Prioridad_CC : 2,
  },
  {
    Id_solicitante : 2,
    Id_evaluador : 3,
    Id_verificador :2,
    Id_evaluador : 1,
    Id_administrador : 2,
    Id_responsable : 1,
    Id_servicio : 3,
    Descripcion_Control_Cambio : "Desarrollo de sistema administrativo IGS",
    Nombre_Control_Cambio : "Sistema IGS Desarrollo",
    Estatus_Control_Cambio : 6,
    Fecha_Solicitud : "07/23/2020",
    Fecha_Inicio : "01/23/2019",
    Fecha_Final :"02/30/2020",
    //Fecha_Verificacion : req.body.Fecha_Verificacion,
    //Estado_cargo : req.body.Estado_cargo,
    Prioridad_CC : 1,
  },
  {
    Id_solicitante : 2,
    Id_evaluador : 3,
    Id_verificador :2,
    Id_evaluador : 1,
    Id_administrador : 2,
    Id_responsable : 1,
    Id_servicio : 1,
    Descripcion_Control_Cambio : "Manuales de procedimientos",
    Nombre_Control_Cambio : "Desarrollo para manuales de procedimientos",
    Estatus_Control_Cambio : 7,
    Fecha_Solicitud : "07/23/2020",
    Fecha_Inicio : "01/23/2019",
    Fecha_Final :"02/30/2020",
    Prioridad_CC : 2,
  }];

module.exports = controlcambio;